project_id = "vkhrrgcbarvssshlhdid"

[functions.analyze-expenses]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.powens-init]
verify_jwt = true

[functions.powens-callback]
verify_jwt = true

[functions.powens-sync]
verify_jwt = true
